### PR TITLE
[TECHNICAL SUPPORT] LPS-45660 and LPS-61428

### PR DESCRIPTION
**Pull request by adamnagy**
https://issues.liferay.com/browse/LPS-55208
causes
https://issues.liferay.com/browse/LPS-61428
which is blocked by:
https://issues.liferay.com/browse/LPS-45660

Dear Vilmos,

Since you work between the holidays I am sending this pull request to you, please review then forward.

LPS-45660 is an old issue and its pull request https://github.com/mhan810/liferay-portal/pull/276 is still open. I rebased it only, plus updated the Javadoc.

The other one is the issue I was working on but was blocked by LPS-45660. This is caused by LPS-55208.

The fix is fairly obvious. The user's modifiedDate doesn't get updated when you want to change only the password, and since there is a separate password check it should solve the issue.

Unfortunately I am not able to test the issue on Master since the modifiedDate keeps changing constantly.

I created a branch where I used the commit of the original fix which cause the regression then rebased your fix of LPS-45660. With this setup you can verify that my fix works.

https://github.com/adamnagy/liferay-portal/tree/LPS-61428-on-LPS-45660-rebased-to-LPS-55208

I will keep an eye on Skype if you have some questions or need something.

Thank you,
Ádám

### CODE REVIEW

**Comment by adamnagy** [comment]
ci:retest

**Comment by vilmospapp** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by vilmospapp** [comment]
Thanks Ádám. I think it's commited finally.

**Comment by adamnagy** [comment]
Sent to: https://github.com/briangreenwald/liferay-portal/pull/13
Then: ?
Then: https://github.com/brianchandotcom/liferay-portal/pull/34703

**Pull request closed without merging**
